version: '3.8'

services:
  moot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - chat-data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2:1b}
    depends_on:
      - ollama
    networks:
      - moot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    container_name: moot-ollama
    ports:
      - '${OLLAMA_PORT:-11434}:11434'
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - moot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  moot-network:
    driver: bridge

volumes:
  ollama-data:
    driver: local
  chat-data:
    driver: local
